"""add_role_and_employee_id_to_auth

Revision ID: 05503dc89fbe
Revises: 9c51dd519220
Create Date: 2026-09-14 14:04:35.292269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05503dc89fbe'
down_revision: Union[str, Sequence[str], None] = '9c51dd519220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('role', sa.String(length=20), server_default='employee', nullable=False))
    op.add_column('auth', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.drop_column('auth', 'employee_id')
    op.drop_column('auth', 'role')
    # ### end Alembic commands ###
