"""create auth table

Revision ID: 50d45708de5f
Revises: 9ac508847ebb
Create Date: 2026-09-04 16:31:00.131672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d45708de5f'
down_revision: Union[str, Sequence[str], None] = '9ac508847ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_username_key'), 'auth', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('auth_username_key'), 'auth', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
